<a href="https://colab.research.google.com/github/anakrantauanalytics/bpjs_healthkathon_2023/blob/main/bpjs_2023_EDA_Sandbox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [ ]:
path_reguler = '/content/gdrive/MyDrive/bpjs hackathon 2023/Reguler'
path_DM = '/content/gdrive/MyDrive/bpjs hackathon 2023/Kontekstual DM'
path_TB = '/content/gdrive/MyDrive/bpjs hackathon 2023/Kontekstual TB'

os.listdir(path_DM)

['DM2019_kepesertaan.dta',
 'DM2020_kepesertaan.dta',
 'DM2021_kepesertaan.dta',
 'DM2021_fkrtldxsekunder.dta',
 'DM2021_fkrtl.dta',
 'DM2021_fktpkapitasi.dta',
 'DM2021_fktpnonkapitasi.dta',
 'Dofiles',
 'Kode diagnosis ICD10']

In [ ]:
import pandas as pd

kepesertaan_cols = ['no_peserta','no_keluarga','tgl_lahir_peserta','hub_klg','jenis_kelamin','status_kawin','kelas_rawat',
                    'segmen_peserta','prov_peserta','kota_kab_peserta',
                    'kepemilikan_faskes','jenis_faskes','prov_faskes','kota_kab_faskes',
                    'bobot','tahun_sampel','status_kepesertaan','tahun_meninggal']
df_kepesertaan_reguler = pd.read_stata(f'{path_reguler}/2015202101_kepesertaan.dta')
df_kepesertaan_dm_1 = pd.read_stata(f'{path_DM}/DM2021_kepesertaan.dta')

df_kepesertaan_reguler.columns = kepesertaan_cols
df_kepesertaan_dm_1.columns = kepesertaan_cols

len(df_kepesertaan_reguler), len(df_kepesertaan_dm_1)

(2305435, 143496)

In [ ]:
df_merge_test = pd.merge(df_kepesertaan_dm_1, df_kepesertaan_reguler, how='left', left_on='no_peserta', right_on='no_peserta')
df_merge_test[df_merge_test['hub_klg_y'].isna() == False]

,no_peserta,no_keluarga_x,tgl_lahir_peserta_x,hub_klg_x,jenis_kelamin_x,status_kawin_x,kelas_rawat_x,segmen_peserta_x,prov_peserta_x,kota_kab_peserta_x,...,prov_peserta_y,kota_kab_peserta_y,kepemilikan_faskes_y,jenis_faskes_y,prov_faskes_y,kota_kab_faskes_y,bobot_y,tahun_sampel_y,status_kepesertaan_y,tahun_meninggal_y
112,61961464,61961464,1965-11-20,PESERTA,PEREMPUAN,KAWIN,KELAS I,PPU,JAWA BARAT,KOTA BANDUNG,...,JAWA BARAT,KOTA BANDUNG,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA BARAT,KOTA BANDUNG,523.475464,2016.0,AKTIF,NaN
119,9369940,100836976,1952-08-03,ISTRI,PEREMPUAN,KAWIN,KELAS I,BUKAN PEKERJA,JAWA BARAT,BANDUNG BARAT,...,JAWA BARAT,BANDUNG BARAT,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA BARAT,BANDUNG BARAT,120.179794,2016.0,AKTIF,NaN
141,26852939,26852939,1962-09-20,PESERTA,LAKI-LAKI,KAWIN,KELAS I,PPU,JAWA BARAT,TASIKMALAYA,...,JAWA BARAT,TASIKMALAYA,SWASTA,KLINIK PRATAMA,JAWA BARAT,TASIKMALAYA,3.991986,2016.0,MENINGGAL,2019.0
359,19429477,19429477,1963-02-25,PESERTA,PEREMPUAN,KAWIN,KELAS I,PPU,GORONTALO,POHUWATO,...,GORONTALO,POHUWATO,SWASTA,DOKTER UMUM,GORONTALO,POHUWATO,52.526131,2016.0,AKTIF,NaN
394,53392025,53392025,1965-12-13,PESERTA,PEREMPUAN,KAWIN,KELAS I,PPU,MALUKU,KOTA AMBON,...,MALUKU,KOTA AMBON,SWASTA,KLINIK PRATAMA,MALUKU,KOTA AMBON,42.231010,2016.0,AKTIF,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142783,380728138,380728138,1963-08-12,PESERTA,LAKI-LAKI,KAWIN,KELAS II,PBPU,KALIMANTAN SELATAN,BARITO KUALA,...,KALIMANTAN SELATAN,BARITO KUALA,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,KALIMANTAN SELATAN,BARITO KUALA,19.550432,2019.0,AKTIF,NaN
142820,100032886,100032886,1959-12-27,PESERTA,LAKI-LAKI,KAWIN,KELAS I,PPU,SUMATERA UTARA,MANDAILING NATAL,...,SUMATERA UTARA,MANDAILING NATAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,SUMATERA UTARA,MANDAILING NATAL,35.297562,2016.0,AKTIF,NaN
142930,95341756,112390948,1947-06-06,ISTRI,PEREMPUAN,KAWIN,KELAS II,BUKAN PEKERJA,JAWA TENGAH,REMBANG,...,JAWA TENGAH,REMBANG,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,JAWA TENGAH,REMBANG,20.695295,2016.0,AKTIF,NaN
143011,33525596,33525596,1965-03-23,PESERTA,LAKI-LAKI,KAWIN,KELAS I,PPU,MALUKU,KOTA TUAL,...,MALUKU,KOTA TUAL,PEMERINTAH KABUPATEN/KOTA,PUSKESMAS,MALUKU,KOTA TUAL,107.363419,2016.0,AKTIF,NaN
143198,97973698,97973698,1951-10-12,PESERTA,LAKI-LAKI,BELUM KAWIN,KELAS I,BUKAN PEKERJA,JAWA TIMUR,KOTA SURABAYA,...,JAWA TIMUR,KOTA SURABAYA,SWASTA,KLINIK PRATAMA,JAWA BARAT,KOTA BANDUNG,210.314636,2016.0,MENINGGAL,2020.0

In [ ]:
# df_kepesertaan_reguler[df_kepesertaan_reguler['no_keluarga'] == '66897393']

# df_kepesertaan_reguler

Empty DataFrame
Columns: [no_peserta, no_keluarga, tgl_lahir_peserta, hub_klg, jenis_kelamin, status_kawin, kelas_rawat, segmen_peserta, prov_peserta, kota_kab_peserta, kepemilikan_faskes, jenis_faskes, prov_faskes, kota_kab_faskes, bobot, tahun_sampel, status_kepesertaan, tahun_meninggal]
Index: []

In [ ]:
df_kepesertaan.PSTV07.value_counts()

KELAS III    61732
KELAS I      54664
KELAS II     27095
9                5
Name: PSTV07, dtype: int64